include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
    - prefer_final_fields
    - prefer_final_locals
    - prefer_const_declarations
    - avoid_returning_null_for_void
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_const
    - unnecessary_new
    - prefer_single_quotes
    - sort_child_properties_last
